/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author HieuThao
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setLocationRelativeTo (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_goimon = new javax.swing.JButton();
        btn_xuat = new javax.swing.JButton();
        btn_nhap = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btn_suco = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(204, 204, 204));
        main.setMinimumSize(new java.awt.Dimension(780, 600));
        main.setOpaque(false);
        main.setLayout(new java.awt.BorderLayout());
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 600));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_goimon.setBackground(new java.awt.Color(153, 153, 255));
        btn_goimon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_goimon.setText("GỌI MÓN");
        btn_goimon.setAlignmentY(0.0F);
        btn_goimon.setBorder(null);
        btn_goimon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(btn_goimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        btn_xuat.setBackground(new java.awt.Color(153, 153, 255));
        btn_xuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_xuat.setText("XỬ LÝ XUẤT");
        btn_xuat.setAlignmentY(0.0F);
        btn_xuat.setBorder(null);
        btn_xuat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(btn_xuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 70));

        btn_nhap.setBackground(new java.awt.Color(153, 153, 255));
        btn_nhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_nhap.setText("XỬ LÝ NHẬP");
        btn_nhap.setAlignmentY(0.0F);
        btn_nhap.setBorder(null);
        btn_nhap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(btn_nhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, 70));

        btn_thoat.setBackground(new java.awt.Color(153, 153, 255));
        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_thoat.setText("ĐĂNG XUẤT");
        btn_thoat.setAlignmentY(0.0F);
        btn_thoat.setBorder(null);
        btn_thoat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 220, 70));

        btn_suco.setBackground(new java.awt.Color(153, 153, 255));
        btn_suco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_suco.setText("SỰ CỐ");
        btn_suco.setAlignmentY(0.0F);
        btn_suco.setBorder(null);
        btn_suco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sucoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_suco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setForeground(new java.awt.Color(102, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 30));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sucoActionPerformed
        // TODO add your handling code here:
        btn_suco.setBackground(new Color(255, 255, 204));
        main.add(new PhieuSuCo());
        setForm(new SuCo(main));
        
    }//GEN-LAST:event_btn_sucoActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login t = new Login();
        t.showLogin();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void setForm(JComponent com) {
        main.removeAll();
        com.setVisible(true);
        main.add(com);
        main.repaint();
        main.revalidate();
        SwingUtilities.getWindowAncestor(main).setVisible(true);
    }
   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goimon;
    private javax.swing.JButton btn_nhap;
    private javax.swing.JButton btn_suco;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xuat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
