/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bll.SuCo_bll;
import dao.ExcuteData;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
import pojo.SuCo;

/**
 *
 * @author HieuThao
 */
public class XuLySuCO extends javax.swing.JPanel {

    /**
     * Creates new form XuLySuCO
     */
    public XuLySuCO() {
        initComponents();
    }
    JComponent com;
    ExcuteData ex;
    public XuLySuCO(JComponent com, ExcuteData ex) {
        initComponents();
        this.com = com;
        this.ex = ex;
        //loadHeading();
        //inittable_SuCo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SuCo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_TaoMoi = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(780, 600));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setOpaque(false);

        tbl_SuCo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_SuCo);

        jPanel1.setLayout(new java.awt.GridLayout());

        btn_TaoMoi.setBackground(new java.awt.Color(255, 102, 255));
        btn_TaoMoi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TaoMoi.setText("Tạo mới");
        btn_TaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_TaoMoi);

        btn_CapNhat.setBackground(new java.awt.Color(102, 255, 102));
        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CapNhat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMoiActionPerformed
        // TODO add your handling code here:
        PhieuSuCo psc = new PhieuSuCo(com, ex);
        psc.setVisible(true);
        com.removeAll();
        // Thêm form PhieuSuCo vào JComponent
        com.add(psc);
        // Cập nhật giao diện
        com.revalidate();
        com.repaint();
        // Hiển thị lại JComponent
        com.setVisible(true);
    }//GEN-LAST:event_btn_TaoMoiActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CapNhatActionPerformed
    DefaultTableModel model ;
    Vector<String> heading = new Vector<String>();
    ArrayList<SuCo> content = new ArrayList<>();
    
    private void loadHeading()
    {
        heading.add("Mã sự cố");
        heading.add("Tên sự cố");
        heading.add("Hình thức");
        heading.add("Chi phí");
        heading.add("Thời gian xảy ra");
        heading.add("Thời gian kết thúc");
        heading.add("Người lập");
        heading.add("Tên loại");
    }
    private void inittable_SuCo()
    {
        model = new DefaultTableModel();
        SuCo_bll xl = new SuCo_bll(ex);
        content = xl.GetData();
        for (SuCo s : content) {
            //model.addRow(new Object[]{, suCo.getTenSuCo()});
        }
        tbl_SuCo.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_TaoMoi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_SuCo;
    // End of variables declaration//GEN-END:variables
}
